/* Generated By:JavaCC: Do not edit this line. CMMParserConstants.java */
package javacc;
/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CMMParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int ELSE = 8;
  /** RegularExpression Id. */
  int WHILE = 9;
  /** RegularExpression Id. */
  int READ = 10;
  /** RegularExpression Id. */
  int WRITE = 11;
  /** RegularExpression Id. */
  int INT = 12;
  /** RegularExpression Id. */
  int REAL = 13;
  /** RegularExpression Id. */
  int CHAR = 14;
  /** RegularExpression Id. */
  int BREAK = 15;
  /** RegularExpression Id. */
  int CONTINUE = 16;
  /** RegularExpression Id. */
  int PRINT = 17;
  /** RegularExpression Id. */
  int SCAN = 18;
  /** RegularExpression Id. */
  int FOR = 19;
  /** RegularExpression Id. */
  int ELSEIF = 20;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 21;
  /** RegularExpression Id. */
  int REAL_LITERAL = 22;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 23;
  /** RegularExpression Id. */
  int CHARS = 24;
  /** RegularExpression Id. */
  int IDENTIFIER = 25;
  /** RegularExpression Id. */
  int LETTER = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"read\"",
    "\"write\"",
    "\"int\"",
    "\"real\"",
    "\"char\"",
    "\"break\"",
    "\"continue\"",
    "\"print\"",
    "\"scan\"",
    "\"for\"",
    "\"else if\"",
    "<INTEGER_LITERAL>",
    "<REAL_LITERAL>",
    "<CHAR_LITERAL>",
    "<CHARS>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"#\"",
    "\"{\"",
    "\";\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"||\"",
    "\"&&\"",
    "\"!\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\"==\"",
    "\"*\"",
    "\"/\"",
  };

}
